# Generated by Django 5.0.1 on 2024-02-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20240118_1523'),
        ('books', '0005_alter_book_options'),
    ]

    operations = [
    ]
